### ISSUE TITLE
运行init出错

### ISSUE THREAD

**Issue by markqiu** [liudengfeng/cswd#4]
geckodriver 版本v0.21.0
```
Traceback (most recent call last):
  File "/home/markqiu/.local/bin/init-stock-data", line 11, in <module>
    load_entry_point('cswd', 'console_scripts', 'init-stock-data')()
  File "/home/markqiu/czipline/src/cswd/scripts/init_db_data.py", line 68, in main
    flush_stock_issue()
  File "/home/markqiu/czipline/src/cswd/cswd/tasks/stock_issue.py", line 32, in flush_stock_issue
    f10 = THSF10()
  File "/home/markqiu/czipline/src/cswd/cswd/websource/ths.py", line 121, in __init__
    self.browser = make_headless_browser()
  File "/home/markqiu/czipline/src/cswd/cswd/websource/_selenium.py", line 19, in make_headless_browser
    browser = webdriver.Firefox(firefoxProfile, options=options)
  File "/home/markqiu/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    keep_alive=True)
  File "/home/markqiu/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/markqiu/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/markqiu/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/markqiu/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by markqiu** [comment]
按照教程安装了selelium和firefox后解决
