### ISSUE TITLE
运行一段时间后报这个错误，重试过多次，如何处理？

### ISSUE THREAD

**Issue by markqiu** [liudengfeng/cswd#5]
Traceback (most recent call last):
  File "/home/markqiu/czipline/src/cswd/cswd/websource/wy.py", line 176, in fetch_cjmx
    df = pd.read_excel(url, **kwds)
  File "/home/markqiu/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "/home/markqiu/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "/home/markqiu/.local/lib/python3.6/site-packages/pandas/io/excel.py", line 307, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/home/markqiu/.local/lib/python3.6/site-packages/pandas/io/excel.py", line 374, in __init__
    io = _urlopen(self._io)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/markqiu/.local/bin/init-stock-data", line 11, in <module>
    load_entry_point('cswd', 'console_scripts', 'init-stock-data')()
  File "/home/markqiu/czipline/src/cswd/scripts/init_db_data.py", line 73, in main
    flush_dealdetail(init=True)
  File "/home/markqiu/czipline/src/cswd/cswd/tasks/stock_dealdetail.py", line 96, in flush_dealdetail
    flush(codes, dates)
  File "/home/markqiu/czipline/src/cswd/cswd/tasks/stock_dealdetail.py", line 56, in flush
    df = fetch_cjmx(code, d)
  File "/home/markqiu/czipline/src/cswd/cswd/websource/base.py", line 61, in wrapper
    return func(*args, **kwargs)
  File "/home/markqiu/czipline/src/cswd/cswd/websource/wy.py", line 178, in fetch_cjmx
    raise NoWebData('网页数据不存在。股票：{}，日期：{}'.format(code, tdate))
cswd.websource.exceptions.NoWebData: 网页数据不存在。股票：000001，日期：2018-07-12

**Comment by liudengfeng** [comment]
抱歉，现在才看邮件。
分时成交明细当前在日线回测中并没有使用，可以忽略。
最近比较忙，没有研究问题原因（估计是网易更改了源代码），请在脚本文件中注释该操作。
________________________________
发件人: 邱承 <notifications@github.com>
发送时间: 2018年7月26日 10:35
收件人: liudengfeng/cswd
抄送: Subscribed
主题: [liudengfeng/cswd] 运行一段时间后报这个错误，重试过多次，如何处理？ (#5)


Traceback (most recent call last):
File "/home/markqiu/czipline/src/cswd/cswd/websource/wy.py", line 176, in fetch_cjmx
df = pd.read_excel(url, **kwds)
File "/home/markqiu/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 178, in wrapper
return func(*args, **kwargs)
File "/home/markqiu/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 178, in wrapper
return func(*args, **kwargs)
File "/home/markqiu/.local/lib/python3.6/site-packages/pandas/io/excel.py", line 307, in read_excel
io = ExcelFile(io, engine=engine)
File "/home/markqiu/.local/lib/python3.6/site-packages/pandas/io/excel.py", line 374, in init
io = _urlopen(self._io)
File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.6/urllib/request.py", line 532, in open
response = meth(req, response)
File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python3.6/urllib/request.py", line 570, in error
return self._call_chain(*args)
File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
result = func(*args)
File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/markqiu/.local/bin/init-stock-data", line 11, in
load_entry_point('cswd', 'console_scripts', 'init-stock-data')()
File "/home/markqiu/czipline/src/cswd/scripts/init_db_data.py", line 73, in main
flush_dealdetail(init=True)
File "/home/markqiu/czipline/src/cswd/cswd/tasks/stock_dealdetail.py", line 96, in flush_dealdetail
flush(codes, dates)
File "/home/markqiu/czipline/src/cswd/cswd/tasks/stock_dealdetail.py", line 56, in flush
df = fetch_cjmx(code, d)
File "/home/markqiu/czipline/src/cswd/cswd/websource/base.py", line 61, in wrapper
return func(*args, **kwargs)
File "/home/markqiu/czipline/src/cswd/cswd/websource/wy.py", line 178, in fetch_cjmx
raise NoWebData('网页数据不存在。股票：{}，日期：{}'.format(code, tdate))
cswd.websource.exceptions.NoWebData: 网页数据不存在。股票：000001，日期：2018-07-12

―

**Comment by markqiu** [comment]
谢谢，一注释掉就可以跑了，谢谢！

**Comment by liudengfeng** [comment]
加我微信ldf10728268，我们有个群，方便一起讨论。
________________________________
发件人: 邱承 <notifications@github.com>
发送时间: 2018年7月28日 5:44
收件人: liudengfeng/cswd
抄送: LDF; Comment
主题: Re: [liudengfeng/cswd] 运行一段时间后报这个错误，重试过多次，如何处理？ (#5)


谢谢，一注释掉就可以跑了，谢谢！

―
